development:
  adapter: mysql
  database: tests
  pool: 5
  encoding: utf8
  username: root
  password: pass

production:
  adapter: mysql
  database: tests
  pool: 5
  encoding: utf8
  username: root
  password: pass